Segmenter.h: Fix compilation error with -std=c++11.
This commit fixes compilation errors due to compilation with std=c++11,
such as:

include/rail_segmentation/Segmenter.h:82:23: error: ‘constexpr’ needed for
in-class initialization of static data member
‘const double rail::segmentation::Segmenter::SAC_EPS_ANGLE’ of
non-integral type [-fpermissive]
   static const double SAC_EPS_ANGLE = 0.15;
                       ^~~~~~~~~~~~~

Signed-off-by: Elvis Dowson <elvis.dowson@gmail.com>